import { describe, expect, it } from "vitest";

import {
  createProxyIconURL,
  createProxyURL,
  getProxyIconTarget,
  getProxyTarget,
  isProxySourcePath,
} from "../src/index";

describe("release proxy", () => {
  it("rewrites GitHub download URLs through the Worker", () => {
    const proxyURL = createProxyURL(
      "https://apps-pick.gcy.workers.dev",
      "https://github.com/czy0729/Bangumi/releases/download/upstream-8.34.3/Bangumi-8.34.3-unsigned.ipa",
    );

    expect(proxyURL).toBe(
      "https://apps-pick.gcy.workers.dev/proxy/czy0729/Bangumi/releases/download/upstream-8.34.3/Bangumi-8.34.3-unsigned.ipa",
    );
  });

  it("rewrites configured icons through the Worker", () => {
    expect(createProxyIconURL("https://apps-pick.gcy.workers.dev", "oliver")).toBe(
      "https://apps-pick.gcy.workers.dev/proxy/icon/oliver",
    );
    expect(getProxyIconTarget("/proxy/icon/joycomic")?.toString()).toBe(
      "https://raw.githubusercontent.com/xiaoqi419/JoyComic/main/assets/app.jpg",
    );
    expect(getProxyIconTarget("/proxy/icon/fluxdo")?.toString()).toBe(
      "https://raw.githubusercontent.com/Lingyan000/fluxdo/main/ios/Runner/Assets.xcassets/AppIcon.appiconset/AppIcon-Light-1024x1024.png",
    );
    expect(getProxyIconTarget("/proxy/icon/han1me-plus")?.toString()).toBe(
      "https://raw.githubusercontent.com/1wc10086/Han1mePlus/main/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024%401x.png",
    );
    expect(getProxyIconTarget("/proxy/icon/hana")?.toString()).toBe(
      "https://raw.githubusercontent.com/celia-sh/Hana/main/Hana/AppIcon.icon/Assets/hana.png",
    );
    expect(getProxyIconTarget("/proxy/icon/loveiwara")?.toString()).toBe(
      "https://raw.githubusercontent.com/FoxSensei001/LoveIwara/master/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024%401x.png",
    );
    expect(getProxyIconTarget("/proxy/icon/oliver")?.toString()).toBe(
      "https://github.com/Ovler-Young.png",
    );
    expect(getProxyIconTarget("/proxy/icon/melox")?.toString()).toBe(
      "https://raw.githubusercontent.com/youshen2/MeloX/main/MeloX/Assets.xcassets/AppIcon.appiconset/AppIcon-1024.png",
    );
    expect(getProxyIconTarget("/proxy/icon/novella")?.toString()).toBe(
      "https://raw.githubusercontent.com/celia-sh/Novella/main/apps/mobile/assets/Novella.icon/Assets/Novella.png",
    );
    expect(getProxyIconTarget("/proxy/icon/oneanime")?.toString()).toBe(
      "https://raw.githubusercontent.com/Predidit/oneAnime/main/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024%401x.png",
    );
    expect(getProxyIconTarget("/proxy/icon/picacomic")?.toString()).toBe(
      "https://raw.githubusercontent.com/ccbkv/PicaComic/4.8.8/ios/Runner/Assets.xcassets/AppIcon.appiconset/AppIcon~ios-marketing.png",
    );
    expect(getProxyIconTarget("/proxy/icon/unknown")).toBeUndefined();
  });

  it("accepts the Source endpoint with or without a trailing slash", () => {
    expect(isProxySourcePath("/proxy")).toBe(true);
    expect(isProxySourcePath("/proxy/")).toBe(true);
    expect(isProxySourcePath("/proxy/owner/repo/releases/download/v1/app.ipa")).toBe(false);
  });

  it("only resolves IPA release assets and their checksum sidecars from configured repositories", () => {
    expect(
      getProxyTarget(
        "/proxy/Lingyan000/fluxdo/releases/download/v0.2.24/fluxdo-unsigned.ipa",
      )?.toString(),
    ).toBe(
      "https://github.com/Lingyan000/fluxdo/releases/download/v0.2.24/fluxdo-unsigned.ipa",
    );
    expect(
      getProxyTarget(
        "/proxy/xiaoqi419/JoyComic/releases/download/v1.0.0/joycomic-unsigned.ipa",
      )?.toString(),
    ).toBe(
      "https://github.com/xiaoqi419/JoyComic/releases/download/v1.0.0/joycomic-unsigned.ipa",
    );
    expect(
      getProxyTarget(
        "/proxy/Lingyan000/fluxdo/releases/download/v0.2.24/fluxdo-unsigned.ipa.sha256",
      )?.toString(),
    ).toBe(
      "https://github.com/Lingyan000/fluxdo/releases/download/v0.2.24/fluxdo-unsigned.ipa.sha256",
    );
    expect(
      getProxyTarget(
        "/proxy/xiaoqi419/JoyComic/releases/download/v1.0.0/joycomic-unsigned.ipa.sha256",
      )?.toString(),
    ).toBe(
      "https://github.com/xiaoqi419/JoyComic/releases/download/v1.0.0/joycomic-unsigned.ipa.sha256",
    );
    expect(
      getProxyTarget(
        "/proxy/czy0729/Bangumi/releases/download/upstream-8.34.3/Bangumi-8.34.3-unsigned.ipa",
      )?.toString(),
    ).toBe(
      "https://github.com/czy0729/Bangumi/releases/download/upstream-8.34.3/Bangumi-8.34.3-unsigned.ipa",
    );
    expect(
      getProxyTarget(
        "/proxy/youshen2/MeloX/releases/download/v0.4.0/MeloX-iOS-unsigned.ipa",
      )?.toString(),
    ).toBe(
      "https://github.com/youshen2/MeloX/releases/download/v0.4.0/MeloX-iOS-unsigned.ipa",
    );
    expect(
      getProxyTarget(
        "/proxy/youshen2/MeloX/releases/download/v0.4.0/MeloX-iOS-unsigned.ipa.sha256",
      )?.toString(),
    ).toBe(
      "https://github.com/youshen2/MeloX/releases/download/v0.4.0/MeloX-iOS-unsigned.ipa.sha256",
    );
    expect(
      getProxyTarget(
        "/proxy/ccbkv/PicaComic/releases/download/4.8.8/PicaComic-4.8.8-new-app-ios-build_no_sign.ipa",
      )?.toString(),
    ).toBe(
      "https://github.com/ccbkv/PicaComic/releases/download/4.8.8/PicaComic-4.8.8-new-app-ios-build_no_sign.ipa",
    );
    expect(
      getProxyTarget(
        "/proxy/FoxSensei001/LoveIwara/releases/download/0.5.1/i_iwara-0.5.1-ios.ipa",
      )?.toString(),
    ).toBe(
      "https://github.com/FoxSensei001/LoveIwara/releases/download/0.5.1/i_iwara-0.5.1-ios.ipa",
    );
    expect(
      getProxyTarget(
        "/proxy/1wc10086/Han1mePlus/releases/download/v1.1.7/iphone.arm64.ipa",
      )?.toString(),
    ).toBe(
      "https://github.com/1wc10086/Han1mePlus/releases/download/v1.1.7/iphone.arm64.ipa",
    );
    expect(
      getProxyTarget(
        "/proxy/celia-sh/Novella/releases/download/v2.3.0/Novella-2.3.0-release.ipa",
      )?.toString(),
    ).toBe(
      "https://github.com/celia-sh/Novella/releases/download/v2.3.0/Novella-2.3.0-release.ipa",
    );
    expect(
      getProxyTarget(
        "/proxy/celia-sh/Hana/releases/download/v1.1.0/Hana-iOS-1.1.0-45-unsigned.ipa",
      )?.toString(),
    ).toBe(
      "https://github.com/celia-sh/Hana/releases/download/v1.1.0/Hana-iOS-1.1.0-45-unsigned.ipa",
    );
    expect(
      getProxyTarget(
        "/proxy/Predidit/oneAnime/releases/download/1.4.7/oneAnime_ios_1.4.7_no_sign.ipa",
      )?.toString(),
    ).toBe(
      "https://github.com/Predidit/oneAnime/releases/download/1.4.7/oneAnime_ios_1.4.7_no_sign.ipa",
    );
    expect(
      getProxyTarget("/proxy/example/other/releases/download/v1.0.0/app.ipa"),
    ).toBeUndefined();
    expect(
      getProxyTarget(
        "/proxy/xiaoqi419/unknown/releases/download/v1.0.0/joycomic-unsigned.ipa",
      ),
    ).toBeUndefined();
    expect(
      getProxyTarget(
        "/proxy/Lingyan000/unknown/releases/download/v0.2.24/fluxdo-unsigned.ipa",
      ),
    ).toBeUndefined();
    expect(
      getProxyTarget(
        "/proxy/youshen2/unknown/releases/download/v0.4.0/MeloX-iOS-unsigned.ipa",
      ),
    ).toBeUndefined();
    expect(
      getProxyTarget("/proxy/Lingyan000/fluxdo/releases/download/v0.2.24/fluxdo.apk"),
    ).toBeUndefined();
    expect(
      getProxyTarget("/proxy/Lingyan000/fluxdo/releases/download/v0.2.24/fluxdo.zip"),
    ).toBeUndefined();
    expect(
      getProxyTarget("/proxy/Lingyan000/fluxdo/releases/download/v0.2.24/fluxdo.sha256"),
    ).toBeUndefined();
    expect(
      getProxyTarget("/proxy/xiaoqi419/JoyComic/releases/download/v1.0.0/joycomic.apk"),
    ).toBeUndefined();
    expect(
      getProxyTarget("/proxy/xiaoqi419/JoyComic/releases/download/v1.0.0/joycomic.sha256"),
    ).toBeUndefined();
    expect(
      getProxyTarget(
        "/proxy/kangyun1994/zhihu-plus-plus-swift/releases/download/v0.1.0/ZhihuPlusPlus-0.1.0-unsigned-final.ipa",
      )?.toString(),
    ).toBe(
      "https://github.com/kangyun1994/zhihu-plus-plus-swift/releases/download/v0.1.0/ZhihuPlusPlus-0.1.0-unsigned-final.ipa",
    );
  });
});
